"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {
  Activity, AlertTriangle, BarChart3, Boxes, CheckCircle2,
  CircleDollarSign, Cloud, Database, HardDrive, LayoutDashboard, Menu,
  RefreshCw, Server, ShieldCheck, Tags, Users, X,
} from "lucide-react";
import {Accounts,AlertHistory,request} from "./management";
import {LiveInventory} from "./live-inventory";
import {LiveTeams} from "./live-teams";

type Account={id:string;display_name:string;provider_account_id:string;connection_status:string;last_collected_at?:string|null};
type Service={service:string;resources:number;complete_rates:number;partial_rates:number;estimated_rates:number;unresolved_rates:number};
type ServiceCost={service:string;intervals:number;priced_intervals:number;unresolved_intervals:number;amount_usd:string|null};
type TrendPoint={bucket_start:string;amount_usd:string|null;priced_intervals:number;unresolved_intervals:number;coverage_status:"PRICED"|"PARTIAL"|"UNRESOLVED"|"NO_OBSERVATION"};
type TrendResponse={period_start:string;period_end:string;bucket_minutes:5;window_minutes:number;points:TrendPoint[];complete_account_cost:false};
type CostResource={id:string;name:string|null;provider_resource_id:string;service:string;region:string;state:string;pricing_status:string;amount_usd:string};
type Limit={id:string;name:string;amount_usd:string;baseline_amount_usd:string;effective_total_usd:string|null;filter_expression:{conditions:unknown[]};observed_subtotal_usd:string|null;evaluation_status:string;alert_status:{status:string;reason?:string}};
type Dashboard={account_name:string;period_start:string;period_end:string;last_collected_at:string|null;last_error:string|null;
  services:Service[];service_costs:ServiceCost[];top_resources:CostResource[];limits:Limit[];
  inventory:{resources:number;untagged_resources:number};cost_summary:{intervals:number;priced_intervals:number;unresolved_intervals:number;observed_subtotal_usd:string|null};
  complete_account_cost_usd:null;alerts_evaluated:true;limitations:string[]};

const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:6});
const colors=["#316cf4","#33a57a","#24a2ae","#7956d8","#df7a3e","#d4aa32","#7d879c"];

function utcDefaults(){const now=new Date();const end=now.toISOString().slice(0,10);return {from:`${end.slice(0,8)}01`,to:end};}
function price(value:string|null){return value===null?"Unavailable":money.format(Number(value));}

function LiveTrend({rows}:{rows:TrendPoint[]}){
  const [selected,setSelected]=useState<number|null>(null);
  if(rows.length===0)return <div className="live-empty-chart"><BarChart3/><b>No observations in this window</b><span>Unavailable periods are not drawn as zero.</span></div>;
  const values=rows.map(row=>row.amount_usd===null?null:Number(row.amount_usd));
  const max=Math.max(...values.filter((value):value is number=>value!==null),.000001);
  const points=rows.map((row,index)=>({x:rows.length===1?369:54+index*(636/(rows.length-1)),y:185-(values[index]??0)/max*145,row,value:values[index]}));
  const segments:string[]=[];let segment:string[]=[];
  const flushSegment=()=>{if(segment.length===1)segments.push(`M ${segment[0]} h .01`);else if(segment.length>1)segments.push(`M ${segment.join(" L ")}`);segment=[];};
  points.forEach(point=>{if(point.value===null)flushSegment();else segment.push(`${point.x} ${point.y}`);});
  flushSegment();
  const unresolvedPath=points.filter(point=>point.row.unresolved_intervals>0).map(point=>`M ${point.x} 188 v 7`).join(" ");
  const timeLabel=(value:string)=>new Date(value).toISOString().slice(5,16).replace("T"," ");
  const choose=(clientX:number,currentTarget:SVGSVGElement)=>{const bounds=currentTarget.getBoundingClientRect();const svgX=(clientX-bounds.left)/bounds.width*720;setSelected(Math.max(0,Math.min(rows.length-1,Math.round((svgX-54)/636*(rows.length-1)))));};
  return <svg className="cost-chart five-minute-chart" viewBox="0 0 720 230" role="img" aria-label="Observed cost in five-minute buckets" tabIndex={0} onPointerMove={event=>choose(event.clientX,event.currentTarget)} onPointerLeave={()=>setSelected(null)} onClick={event=>choose(event.clientX,event.currentTarget)} onKeyDown={event=>{if(event.key==="Escape")setSelected(null);if(event.key==="ArrowLeft")setSelected(value=>Math.max(0,(value??rows.length)-1));if(event.key==="ArrowRight")setSelected(value=>Math.min(rows.length-1,(value??-1)+1));}}>
    {[0,.25,.5,.75,1].map(part=><g key={part}><line x1="54" y1={185-part*145} x2="690" y2={185-part*145} stroke="#e7ebf3" strokeDasharray="3 5"/><text x="48" y={189-part*145} textAnchor="end">{money.format(max*part)}</text></g>)}
    {segments.map((path,index)=><path key={index} d={path} fill="none" stroke="#316cf4" strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>)}
    <path d={unresolvedPath} fill="none" stroke="#d78a25" strokeWidth="2"/>
    {[0,Math.floor((rows.length-1)/2),rows.length-1].map((index,position)=><text key={position} x={points[index].x} y="215" textAnchor={position===0?"start":position===2?"end":"middle"}>{timeLabel(rows[index].bucket_start)}</text>)}
    {selected!==null&&<g pointerEvents="none" role="tooltip"><line x1={points[selected].x} y1="35" x2={points[selected].x} y2="185" stroke="#7891c4" strokeDasharray="3 3"/><circle cx={points[selected].x} cy={points[selected].value===null?185:points[selected].y} r="4" fill="white" stroke={points[selected].value===null?"#d78a25":"#316cf4"} strokeWidth="2"/><rect x={Math.max(54,Math.min(points[selected].x-90,500))} y="0" width="190" height="64" rx="7" fill="#15223a"/><text x={Math.max(64,Math.min(points[selected].x-80,510))} y="19" style={{fill:"white",fontSize:12}}>{new Date(rows[selected].bucket_start).toISOString().replace("T"," ").slice(0,16)} UTC</text><text x={Math.max(64,Math.min(points[selected].x-80,510))} y="38" style={{fill:"white",fontSize:12}}>{points[selected].value===null?"Cost unavailable":`${money.format(points[selected].value as number)} observed`}</text><text x={Math.max(64,Math.min(points[selected].x-80,510))} y="55" style={{fill:"#f1bd69",fontSize:11}}>{rows[selected].unresolved_intervals} unresolved · {rows[selected].coverage_status}</text></g>}
  </svg>;
}

export function LiveDashboard({onSample}:{onSample:()=>void}){
  const [accounts,setAccounts]=useState<Account[]>([]);const [account,setAccount]=useState("");
  const [data,setData]=useState<Dashboard|null>(null);const [error,setError]=useState("");
  const [trend,setTrend]=useState<TrendResponse|null>(null);const [trendWindow,setTrendWindow]=useState(1_440);const [trendError,setTrendError]=useState("");const [trendLoading,setTrendLoading]=useState(true);
  const [view,setView]=useState<"overview"|"teams"|"inventory"|"accounts"|"alerts">("overview");
  const [from,setFrom]=useState("");const [to,setTo]=useState("");const [queryRange,setQueryRange]=useState("");const [applied,setApplied]=useState(0);
  const [loading,setLoading]=useState(true);const [mobile,setMobile]=useState(false);
  useEffect(()=>{let active=true;request<Account[]>("/api/v1/accounts").then(rows=>{if(!active)return;const defaults=utcDefaults();setFrom(defaults.from);setTo(defaults.to);setQueryRange(`${defaults.from}/${defaults.to}`);setAccounts(rows);const preferred=rows.find(item=>item.connection_status==="CONNECTED")??rows[0];if(preferred)setAccount(preferred.id);else setLoading(false);}).catch(reason=>{if(active){setError(reason.message);setLoading(false);}});return()=>{active=false;};},[]);
  const reload=useCallback(()=>{setLoading(true);setError("");setTrendLoading(true);setTrendError("");setApplied(value=>value+1);},[]);
  useEffect(()=>{if(!account||!queryRange)return;let active=true;const [start,end]=queryRange.split("/");request<Dashboard>(`/api/v1/accounts/${account}/overview?start_date=${start}&end_date=${end}`).then(result=>{if(active){setData(result);setError("");}}).catch(reason=>{if(active){setError(reason.message);setData(null);}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[account,queryRange,applied]);
  useEffect(()=>{if(!account)return;let active=true;request<TrendResponse>(`/api/v1/accounts/${account}/cost-trend?window_minutes=${trendWindow}`).then(result=>{if(active)setTrend(result);}).catch(reason=>{if(active){setTrend(null);setTrendError(reason.message);}}).finally(()=>{if(active)setTrendLoading(false);});return()=>{active=false;};},[account,trendWindow,applied]);
  const selected=accounts.find(item=>item.id===account);
  const intervalCoverage=data?.cost_summary.intervals?data.cost_summary.priced_intervals/data.cost_summary.intervals*100:0;
  const maxService=useMemo(()=>Math.max(...(data?.service_costs.map(item=>Number(item.amount_usd||0))??[0]),.000001),[data]);
  const nav=[{id:"overview" as const,label:"Live overview",icon:LayoutDashboard},{id:"teams" as const,label:"Teams & limits",icon:Users},{id:"inventory" as const,label:"Live inventory",icon:Boxes},{id:"alerts" as const,label:"Alert history",icon:AlertTriangle},{id:"accounts" as const,label:"Cloud accounts",icon:Database}];
  return <div className="shell live-shell">
    <aside className={`sidebar ${mobile?"open":""}`}><div className="brand"><span className="logo"><Cloud size={19}/></span><span>Cloud<span>Scope</span></span><button className="close" onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div>
      <nav>{nav.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>{setView(item.id);setMobile(false);}}><item.icon size={18}/>{item.label}</button>)}</nav>
      <div className="side-caption">REFERENCE</div><nav><button onClick={onSample}><BarChart3 size={18}/>Sample dashboard</button></nav>
      <div className="sidebar-foot"><div className="health"><span><i/>Live collector</span><small>{selected?.connection_status??"No account selected"}</small></div></div>
    </aside>
    {mobile&&<button className="backdrop" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}
    <main className="main"><header className="topbar"><button className="menu" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="crumb"><Activity size={15}/><strong>Live read-only pilot</strong></div><div className="top-actions"><select aria-label="AWS account" value={account} onChange={event=>{setLoading(true);setTrendLoading(true);setError("");setTrendError("");setAccount(event.target.value);setData(null);setTrend(null);}}><option value="">Select account</option>{accounts.map(item=><option value={item.id} key={item.id}>{item.display_name}</option>)}</select><button className="refresh" disabled={!account||loading} onClick={reload}><RefreshCw size={16}/>{loading?"Loading…":"Refresh"}</button></div></header>
      <section className="content">
        {view==="overview"&&<><div className="title-row"><div><div className="eyebrow"><CheckCircle2 size={14}/>LIVE OBSERVATIONS</div><h1>{data?.account_name??selected?.display_name??"Cloud cost overview"}</h1><p>Observed local subtotals. Team alerts use a declared first-month baseline plus complete observations after team creation.</p></div><form className="live-date" onSubmit={event=>{event.preventDefault();setQueryRange(`${from}/${to}`);reload();}}><label>FROM<input type="date" required value={from} onChange={event=>setFrom(event.target.value)}/></label><label>TO<input type="date" required value={to} onChange={event=>setTo(event.target.value)}/></label><button type="submit">Apply</button></form></div>
          {error&&<div className="guardrail error"><AlertTriangle/><div><b>Live data unavailable</b><span>{error}</span></div></div>}
          {!error&&accounts.length===0&&!loading&&<article className="panel management"><h2>No account registered</h2><p>Open Cloud accounts to register and test an AWS account.</p><button onClick={()=>setView("accounts")}>Open Cloud accounts</button></article>}
          {data&&<><div className="guardrail amber"><ShieldCheck/><div><b>Automatic alerts active with safety gates</b><span>80% and 100% thresholds run after collection. Incomplete, stale, partial or assumed costs cannot publish.</span></div><span>FAIL CLOSED</span></div>
            <div className="kpis"><article><div className="kpi-icon blue"><CircleDollarSign/></div><span>OBSERVED SUBTOTAL</span><strong>{price(data.cost_summary.observed_subtotal_usd)}</strong><small>Since collection began within selected range</small></article><article><div className="kpi-icon violet"><Server/></div><span>STORED RESOURCES</span><strong>{data.inventory.resources}</strong><small>Latest normalized inventory</small></article><article><div className="kpi-icon green"><ShieldCheck/></div><span>PRICED INTERVALS</span><strong>{data.cost_summary.priced_intervals}</strong><small>{intervalCoverage.toFixed(1)}% interval coverage</small></article><article><div className="kpi-icon amber"><Tags/></div><span>UNTAGGED RESOURCES</span><strong>{data.inventory.untagged_resources}</strong><small>Latest observation has no tags</small></article></div>
            <div className="overview-grid"><article className="panel chart-panel"><div className="panel-head"><div><h2>Observed cost trend</h2><span>Cost per 5-minute bucket • USD</span></div><label className="trend-window">WINDOW<select aria-label="Observed cost trend window" value={trendWindow} onChange={event=>{setTrendLoading(true);setTrendError("");setTrendWindow(Number(event.target.value));}}><option value={60}>1 hour</option><option value={360}>6 hours</option><option value={1440}>24 hours</option><option value={4320}>3 days</option><option value={10080}>7 days</option></select></label></div><div className="chart">{trendLoading?<div className="live-empty-chart"><b>Loading five-minute trend…</b></div>:trendError?<div className="live-empty-chart trend-error"><AlertTriangle/><b>Trend unavailable</b><span>{trendError}</span></div>:<LiveTrend rows={trend?.points??[]}/>}</div><div className="chart-foot"><span><i/>Priced observations; line gaps mean unavailable</span><span>{trend?`${new Date(trend.period_start).toISOString().slice(0,16).replace("T"," ")} → ${new Date(trend.period_end).toISOString().slice(0,16).replace("T"," ")} UTC`:"Five-minute resolution"}</span></div></article><article className="panel services"><div className="panel-head"><div><h2>Observed cost by service</h2><span>Not complete spend</span></div></div>{data.service_costs.map((item,index)=><div className="service-row live-service" key={item.service}><span className="service-rank">{index+1}</span><span className="service-dot" style={{background:colors[index%colors.length]}}/><b>{item.service.toUpperCase()}</b><div className="service-bar"><i style={{width:`${Number(item.amount_usd||0)/maxService*100}%`,background:colors[index%colors.length]}}/></div><strong>{price(item.amount_usd)}</strong><small>{item.unresolved_intervals} unresolved</small></div>)}</article></div>
            <div className="lower-grid"><article className="panel limit-card"><div className="panel-head"><div><h2>Monthly team limits</h2><span>Automatic 80% / 100% evaluation</span></div><button onClick={()=>setView("teams")}>Manage teams</button></div>{data.limits.length===0?<p>No local team limit is configured.</p>:data.limits.map(limit=><div className="live-limit" key={limit.id}><div><b>{limit.name}</b><span>{limit.alert_status.reason?.replaceAll("_"," ")??`${limit.filter_expression.conditions.length} tag conditions`}</span><small>Baseline {price(limit.baseline_amount_usd)} + observed {price(limit.observed_subtotal_usd)}</small></div><strong>{price(limit.effective_total_usd)} <small>/ {price(limit.amount_usd)}</small></strong><span className={`pill ${limit.evaluation_status==="PUBLISHED"?"danger":limit.evaluation_status==="BELOW_THRESHOLD"?"success":"warning"}`}>{limit.evaluation_status.replaceAll("_"," ")}</span></div>)}<p className="muted-copy">Declared baselines are user-supplied. Post-creation cost evidence must still be complete and fresh before an alert can publish.</p></article><article className="panel quality-card"><div className="panel-head"><div><h2>Rate coverage</h2><span>Latest resource observations</span></div></div><div className="quality-list">{data.services.map(item=><span key={item.service}><HardDrive/>{item.service.toUpperCase()} — {item.resources} resources <b>{item.complete_rates} complete · {item.partial_rates} partial · {item.estimated_rates} assumed · {item.unresolved_rates} unresolved</b></span>)}</div></article></div>
            <article className="panel table-panel"><div className="panel-head"><div><h2>Highest observed resource subtotals</h2><span>Priced intervals in selected range</span></div></div><div className="table-wrap"><table><thead><tr><th>Resource</th><th>Service</th><th>Region</th><th>State</th><th>Rate status</th><th className="right">Observed subtotal</th></tr></thead><tbody>{data.top_resources.map(item=><tr key={item.id}><td><b>{item.name||item.provider_resource_id}</b><br/><small>{item.provider_resource_id}</small></td><td>{item.service.toUpperCase()}</td><td>{item.region}</td><td>{item.state}</td><td>{item.pricing_status}</td><td className="right cost">{price(item.amount_usd)}</td></tr>)}</tbody></table></div>{data.top_resources.length===0&&<p>No priced resource intervals exist for this range.</p>}</article>
            <details className="panel live-limitations"><summary>Coverage limitations</summary><ul>{data.limitations.map(item=><li key={item}>{item}</li>)}</ul></details><p className="live-freshness">Last successful collection: {data.last_collected_at??"not collected"}</p></>}
        </>}
        {view==="teams"&&<><div className="title-row"><div><div className="eyebrow"><Users size={14}/>LIVE TEAM OWNERSHIP</div><h1>Teams, limits and resources</h1><p>Define exact tag-based ownership, preview matches, and inspect each team.</p></div><form className="live-date" onSubmit={event=>{event.preventDefault();setQueryRange(`${from}/${to}`);reload();}}><label>FROM<input type="date" required value={from} onChange={event=>setFrom(event.target.value)}/></label><label>TO<input type="date" required value={to} onChange={event=>setTo(event.target.value)}/></label><button type="submit">Apply</button></form></div><LiveTeams key={account} account={account} range={queryRange} revision={applied} onCreated={reload}/></>}
        {view==="inventory"&&<><div className="title-row"><div><div className="eyebrow"><Activity size={14}/>LIVE INVENTORY</div><h1>Resources and matched rates</h1><p>Stored locally from the read-only collector.</p></div></div><LiveInventory accounts={accounts}/></>}
        {view==="alerts"&&<><div className="title-row"><div><div className="eyebrow"><AlertTriangle size={14}/>AUTOMATIC NOTIFICATIONS</div><h1>Alert history</h1><p>Durable 80% and 100% threshold events and SNS delivery state.</p></div></div><AlertHistory/></>}
        {view==="accounts"&&<><div className="title-row"><div><div className="eyebrow"><Activity size={14}/>ACCOUNT MANAGEMENT</div><h1>Cloud accounts</h1><p>Connection, collection schedule and onboarding controls.</p></div></div><Accounts/></>}
      </section>
    </main>
  </div>;
}
