"use client";

import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Plus,ShieldCheck,Tags,Trash2,Users} from "lucide-react";
import {request} from "./management";

type Rule={key:string;operator:"EQUALS"|"NOT_EQUALS"|"EXISTS"|"NOT_EXISTS";value:string};
type TagNode={kind:"tag";key:string;operator:Rule["operator"];value?:string};
type GroupNode={kind:"group";operator:"AND"|"OR";conditions:(TagNode|GroupNode)[]};
type FilterExpression=GroupNode;
type Team={id:string;name:string;amount_usd:string;baseline_amount_usd:string;effective_total_usd:string|null;filter_expression:FilterExpression;resource_count:number;resources_with_rates:number;intervals:number;priced_intervals:number;unresolved_intervals:number;observed_subtotal_usd:string|null;evaluation_status:string;alert_status:{status:string;reason?:string}};
type Resource={id:string;name:string|null;provider_resource_id:string;provider_resource_type:string;region:string;availability_zone:string|null;state:string;last_seen:string;current_member:boolean;intervals:number;unresolved_intervals:number;priced_seconds:string;observed_subtotal_usd:string|null;metadata:{tags?:Record<string,string>;pricing?:{status?:string}}};
type TeamList={period_start:string;period_end:string;teams:Team[];alerts_evaluated:true;automatic_alerts_enabled:true};
type Preview={matching_resources:number;sample:{id:string;name:string|null;provider_resource_id:string;provider_resource_type:string;region:string;state:string;pricing_status:string|null}[];sample_limit:number};
type TeamTrend={bucket_start:string;amount_usd:string|null;priced_intervals:number;unresolved_intervals:number;coverage_status:"PRICED"|"PARTIAL"|"UNRESOLVED"|"NO_OBSERVATION"};
type TeamResources={team_id:string;team_name:string;filter_expression:FilterExpression;period_start:string;period_end:string;trend_bucket:"hour"|"day";cost_trend:TeamTrend[];resources:Resource[]};
type CostHistory={team_id:string;team_name:string;resource:{id:string;name:string|null;provider_resource_id:string;provider_resource_type:string;region:string;state:string};period_start:string;period_end:string;summary:{intervals:number;priced_intervals:number;unresolved_intervals:number;priced_seconds:string;observed_subtotal_usd:string|null};intervals:{usage_start:string;usage_end:string;duration_seconds:string;amount_usd:string|null;effective_hourly_usd:string|null;basis:string;reason:string;tags:Record<string,string>}[];cost_status:"PARTIAL_OBSERVED_ONLY"};

const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:6});
const blankRule=():Rule=>({key:"Team",operator:"EQUALS",value:""});
const showMoney=(value:string|null)=>value===null?"Unavailable":money.format(Number(value));
function expression(operator:"AND"|"OR",rules:Rule[]):FilterExpression{return {kind:"group",operator,conditions:rules.map(rule=>({kind:"tag",key:rule.key.trim(),operator:rule.operator,...(rule.operator==="EQUALS"||rule.operator==="NOT_EQUALS"?{value:rule.value.trim()}:{})}))};}
function describeNode(node:TagNode|GroupNode):string{if(node.kind==="group")return `(${node.conditions.map(describeNode).join(` ${node.operator} `)})`;return node.operator==="EXISTS"?`${node.key} exists`:node.operator==="NOT_EXISTS"?`${node.key} is absent`:`${node.key} ${node.operator==="EQUALS"?"=":"≠"} ${node.value}`;}
function describeFilter(filter:FilterExpression){const value=describeNode(filter);return value.slice(1,-1);}
function duration(value:string|number){const seconds=Number(value);if(!Number.isFinite(seconds))return "Unavailable";const hours=Math.floor(seconds/3600);const minutes=Math.floor((seconds%3600)/60);const remaining=Math.round(seconds%60);return `${hours}h ${minutes}m ${remaining}s`;}
function alertLabel(team:Team){const status=team.evaluation_status;return status==="PUBLISHED"?"ALERT SENT":status==="PENDING"||status==="RETRY"?"DELIVERY PENDING":status==="BELOW_THRESHOLD"?"MONITORING":status==="AWAITING_CONFIRMATION"?"CONFIRMING":"BLOCKED";}

function TeamConsumptionChart({rows,bucket}:{rows:TeamTrend[];bucket:"hour"|"day"}){
  const [selected,setSelected]=useState<number|null>(null);
  if(rows.length===0)return <div className="live-empty-chart"><b>No observations in this range</b><span>Unavailable periods are not drawn as zero.</span></div>;
  const values=rows.map(row=>row.amount_usd===null?null:Number(row.amount_usd));
  const max=Math.max(...values.filter((value):value is number=>value!==null),.000001);
  const slot=636/rows.length;const width=Math.max(2,Math.min(28,slot*.62));
  const labelEvery=Math.max(1,Math.ceil(rows.length/7));
  const label=(value:string)=>bucket==="hour"?value.slice(5,13).replace("T"," "):value.slice(5,10);
  return <svg className="cost-chart team-cost-chart" viewBox="0 0 720 230" role="img" aria-label={`Team observed cost by ${bucket}`}>
    <defs><pattern id="teamUnresolved" width="5" height="5" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><line x1="0" y1="0" x2="0" y2="5" stroke="#d78a25" strokeWidth="2"/></pattern></defs>
    {[0,.25,.5,.75,1].map(part=><g key={part}><line x1="54" y1={185-part*145} x2="690" y2={185-part*145} stroke="#e7ebf3" strokeDasharray="3 5"/><text x="48" y={189-part*145} textAnchor="end">{money.format(max*part)}</text></g>)}
    {rows.map((row,index)=>{const x=54+index*slot+slot/2;const value=values[index];const height=value===null?0:value/max*145;return <g key={row.bucket_start}>
      {value!==null&&<rect x={x-width/2} y={185-height} width={width} height={Math.max(height,1)} rx="2" fill="#316cf4"/>}
      {row.coverage_status==="PARTIAL"||row.coverage_status==="UNRESOLVED"?<rect x={x-width/2} y="188" width={width} height="7" fill="url(#teamUnresolved)"/>:null}
      {index%labelEvery===0&&<text x={x} y="215" textAnchor="middle">{label(row.bucket_start)}</text>}
      <rect x={54+index*slot} y="25" width={slot} height="175" fill="transparent" tabIndex={0} role="button" aria-label={`${row.bucket_start}: ${value===null?"cost unavailable":money.format(value)}, ${row.unresolved_intervals} unresolved intervals`} onPointerEnter={()=>setSelected(index)} onPointerLeave={()=>setSelected(null)} onFocus={()=>setSelected(index)} onBlur={()=>setSelected(null)} onClick={()=>setSelected(index)} onKeyDown={event=>{if(event.key==="Escape")setSelected(null);if(event.key==="Enter"||event.key===" ")setSelected(index);}}/>
    </g>;})}
    {selected!==null&&<g pointerEvents="none" role="tooltip"><rect x={Math.min(54+selected*slot,505)} y="0" width="200" height="64" rx="7" fill="#15223a"/><text x={Math.min(54+selected*slot,505)+10} y="19" style={{fill:"white",fontSize:11}}>{rows[selected].bucket_start}</text><text x={Math.min(54+selected*slot,505)+10} y="38" style={{fill:"white",fontSize:11}}>{values[selected]===null?"Cost unavailable":`${money.format(values[selected] as number)} observed`}</text><text x={Math.min(54+selected*slot,505)+10} y="55" style={{fill:"#f1bd69",fontSize:10}}>{rows[selected].unresolved_intervals} unresolved · {rows[selected].coverage_status}</text></g>}
  </svg>;
}

export function LiveTeams({account,range,revision,onCreated}:{account:string;range:string;revision:number;onCreated?:()=>void}){
  const [data,setData]=useState<TeamList|null>(null);const [selected,setSelected]=useState("");const [resources,setResources]=useState<TeamResources|null>(null);const [history,setHistory]=useState<CostHistory|null>(null);
  const [name,setName]=useState("");const [amount,setAmount]=useState("");const [baseline,setBaseline]=useState("");const [operator,setOperator]=useState<"AND"|"OR">("AND");const [rules,setRules]=useState<Rule[]>([blankRule()]);
  const [preview,setPreview]=useState<Preview|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [saved,setSaved]=useState(0);
  const filter=useMemo(()=>expression(operator,rules),[operator,rules]);
  const valid=rules.length>0&&rules.every(rule=>rule.key.trim()&&((rule.operator==="EXISTS"||rule.operator==="NOT_EXISTS")||rule.value.trim()));
  useEffect(()=>{if(!account||!range)return;let active=true;const [start,end]=range.split("/");request<TeamList>(`/api/v1/accounts/${account}/teams?start_date=${start}&end_date=${end}`).then(result=>{if(active){setData(result);setError("");}}).catch(reason=>{if(active)setError(reason.message);});return()=>{active=false;};},[account,range,revision,saved]);
  async function previewMatches(){if(!valid)return;setBusy("preview");setError("");try{setPreview(await request<Preview>(`/api/v1/accounts/${account}/teams/preview`,{method:"POST",body:JSON.stringify({filter_expression:filter})}));}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  async function saveTeam(event:React.FormEvent){event.preventDefault();if(!valid)return;setBusy("save");setError("");try{await request(`/api/v1/accounts/${account}/teams`,{method:"POST",body:JSON.stringify({name,amount_usd:amount,baseline_amount_usd:baseline||"0",filter_expression:filter})});setName("");setAmount("");setBaseline("");setRules([blankRule()]);setOperator("AND");setPreview(null);setSaved(value=>value+1);onCreated?.();}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  async function openTeam(team:Team){const [start,end]=range.split("/");setSelected(team.id);setHistory(null);setBusy(`team:${team.id}`);setError("");try{setResources(await request<TeamResources>(`/api/v1/accounts/${account}/teams/${team.id}/resources?start_date=${start}&end_date=${end}`));}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  async function deleteTeam(team:Team){if(!window.confirm(`Remove team "${team.name}" and its local limit from active views? AWS resources will not be modified.`))return;setBusy(`delete:${team.id}`);setError("");try{await request(`/api/v1/accounts/${account}/teams/${team.id}`,{method:"DELETE"});if(selected===team.id){setSelected("");setResources(null);setHistory(null);}setSaved(value=>value+1);onCreated?.();}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  async function openHistory(resource:Resource){if(!resources)return;const [start,end]=range.split("/");setBusy(`history:${resource.id}`);setError("");try{setHistory(await request<CostHistory>(`/api/v1/accounts/${account}/teams/${resources.team_id}/resources/${resource.id}/cost-intervals?start_date=${start}&end_date=${end}`));}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  function changeRule(index:number,patch:Partial<Rule>){setRules(current=>current.map((rule,position)=>position===index?{...rule,...patch}:rule));setPreview(null);}
  if(!account)return <article className="panel management"><h2>Teams</h2><p>Select a connected AWS account first.</p></article>;
  return <div className="live-teams">
    <div className="guardrail amber"><ShieldCheck/><div><b>Automatic 80% and 100% alerts are active</b><span>The first month uses the declared baseline plus complete observations after team creation. Missing, stale, partial or assumed evidence blocks publication.</span></div><span>FAIL CLOSED</span></div>
    {error&&<div className="guardrail error" role="alert"><AlertTriangle/><div><b>Team operation failed</b><span>{error}</span></div></div>}
    <article className="panel team-builder"><div className="panel-head"><div><h2>Create team</h2><span>Local definition for this AWS account</span></div></div>
      <form onSubmit={saveTeam}><div className="team-basics"><label>Team name<input required maxLength={100} value={name} onChange={event=>setName(event.target.value)} placeholder="HPC Production"/></label><label>Monthly limit (USD)<input required type="number" min="0.000001" step="0.000001" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="5000.00"/></label><label>Existing MTD baseline (USD)<input type="number" min="0" step="0.000001" value={baseline} onChange={event=>setBaseline(event.target.value)} placeholder="0.00"/><small>User-declared cost from UTC month start until this team is created. It applies only to the first month and is shown separately in alerts.</small></label></div>
        <div className="rule-heading"><div><b>Resource tag conditions</b><span>Every rule is evaluated exactly and case-sensitively against AWS tag keys and values.</span></div><label>Match<select value={operator} onChange={event=>{setOperator(event.target.value as "AND"|"OR");setPreview(null);}}><option value="AND">ALL conditions (AND)</option><option value="OR">ANY condition (OR)</option></select></label></div>
        <div className="rule-list">{rules.map((rule,index)=><div className="rule-row" key={index}><span>{index===0?"WHERE":operator}</span><input aria-label={`Tag key ${index+1}`} required value={rule.key} onChange={event=>changeRule(index,{key:event.target.value})} placeholder="Tag key"/><select aria-label={`Comparison ${index+1}`} value={rule.operator} onChange={event=>changeRule(index,{operator:event.target.value as Rule["operator"]})}><option value="EQUALS">equals</option><option value="NOT_EQUALS">does not equal</option><option value="EXISTS">exists</option><option value="NOT_EXISTS">does not exist</option></select>{(rule.operator==="EQUALS"||rule.operator==="NOT_EQUALS")&&<input aria-label={`Tag value ${index+1}`} required value={rule.value} onChange={event=>changeRule(index,{value:event.target.value})} placeholder="Tag value"/>}<button type="button" className="icon-action" disabled={rules.length===1} onClick={()=>{setRules(current=>current.filter((_,position)=>position!==index));setPreview(null);}} aria-label={`Remove condition ${index+1}`}><Trash2/></button></div>)}</div>
        <div className="builder-actions"><button type="button" onClick={()=>setRules(current=>[...current,blankRule()])} disabled={rules.length>=20}><Plus/>Add condition</button><button type="button" disabled={!valid||Boolean(busy)} onClick={previewMatches}>{busy==="preview"?"Checking…":"Preview matched resources"}</button><button type="submit" disabled={!valid||!name.trim()||!amount||Boolean(busy)}>{busy==="save"?"Creating…":"Create team and limit"}</button></div>
      </form>
      {preview&&<div className="match-preview"><b>{preview.matching_resources} current resources match</b><span>{describeFilter(filter)}</span>{preview.matching_resources===0&&<em>No team will be created until you explicitly submit; check exact tag casing and values.</em>}<div className="preview-chips">{preview.sample.map(row=><span key={row.id}>{row.provider_resource_type.toUpperCase()} · {row.name||row.provider_resource_id}</span>)}</div>{preview.matching_resources>preview.sample_limit&&<small>Showing the first {preview.sample_limit} resources.</small>}</div>}
    </article>
    <div className="team-grid live-team-grid">{data?.teams.map(team=>{const coverage=team.intervals?team.priced_intervals/team.intervals*100:0;const label=alertLabel(team);return <article className={`panel team-card team-select ${selected===team.id?"selected":""}`} key={team.id}><div className="team-head"><span><Users/></span><div><h2>{team.name}</h2><p>{describeFilter(team.filter_expression)}</p></div><span title={team.alert_status.reason?.replaceAll("_"," ")} className={`pill ${label==="ALERT SENT"?"danger":label==="MONITORING"?"success":"warning"}`}>{label}</span><button type="button" className="team-delete" disabled={Boolean(busy)} onClick={()=>void deleteTeam(team)} aria-label={`Delete ${team.name}`}><Trash2/></button></div><strong>{showMoney(team.effective_total_usd)} <small>/ {showMoney(team.amount_usd)}</small></strong><p className="team-cost-parts">Declared baseline {showMoney(team.baseline_amount_usd)} + observed after creation {showMoney(team.observed_subtotal_usd)}</p><div className="team-facts"><span><b>{team.resource_count}</b> current resources</span><span><b>{coverage.toFixed(1)}%</b> priced intervals</span><span><b>{team.unresolved_intervals}</b> unresolved intervals</span></div>{team.alert_status.reason&&<small>Alert gate: {team.alert_status.reason.replaceAll("_"," ")}</small>}<button type="button" className="team-open" disabled={Boolean(busy)} onClick={()=>void openTeam(team)}>{busy===`team:${team.id}`?"Loading resources…":"Open matched resources"}</button></article>;})}</div>
    {data&&data.teams.length===0&&<article className="panel empty-team"><Tags/><h2>No teams configured</h2><p>Create a team above, preview the exact tag match, then save its monthly limit.</p></article>}
    {resources&&<><article className="panel chart-panel team-consumption"><div className="panel-head"><div><h2>{resources.team_name} consumption</h2><span>Observed cost per {resources.trend_bucket} · selected UTC range</span></div></div><div className="chart"><TeamConsumptionChart rows={resources.cost_trend} bucket={resources.trend_bucket}/></div><div className="chart-foot"><span><i/>Blue: priced observed cost</span><span className="unresolved-legend">Striped: unresolved intervals · unavailable is not zero</span></div></article><article className="panel table-panel team-resources"><div className="panel-head"><div><h2>{resources.team_name} resources</h2><span>{resources.resources.length} current or historical matches in the selected period · {describeFilter(resources.filter_expression)}</span></div></div><div className="table-wrap"><table><thead><tr><th>Resource</th><th>Service</th><th>Membership</th><th>State</th><th>Priced duration</th><th>Intervals</th><th>Unresolved</th><th>Observed subtotal</th><th>History</th></tr></thead><tbody>{resources.resources.map(row=><tr key={row.id}><td><b>{row.name||row.provider_resource_id}</b><br/><small>{row.provider_resource_id} · {row.region}</small></td><td>{row.provider_resource_type.toUpperCase()}</td><td>{row.current_member?"Current":"Historical"}</td><td>{row.state}</td><td>{duration(row.priced_seconds)}</td><td>{row.intervals}</td><td>{row.unresolved_intervals}</td><td>{showMoney(row.observed_subtotal_usd)}</td><td><button className="table-action" disabled={Boolean(busy)} onClick={()=>void openHistory(row)}>{busy===`history:${row.id}`?"Loading…":"View history"}</button></td></tr>)}</tbody></table></div>{resources.resources.length===0&&<p>No current or historical resources match this team definition in the selected period.</p>}</article></>}
    {history&&<article className="panel table-panel cost-history"><div className="panel-head"><div><h2>{history.resource.name||history.resource.provider_resource_id} cost history</h2><span>Observed intervals only · {history.period_start.slice(0,10)} → {history.period_end.slice(0,10)}</span></div></div><div className="history-summary"><span><b>{showMoney(history.summary.observed_subtotal_usd)}</b> observed subtotal</span><span><b>{duration(history.summary.priced_seconds)}</b> priced duration</span><span><b>{history.summary.priced_intervals}</b> priced intervals</span><span><b>{history.summary.unresolved_intervals}</b> unresolved intervals</span></div><div className="guardrail amber history-warning"><AlertTriangle/><div><b>Not complete lifetime or invoice history</b><span>History begins with CloudScope observations. Gaps and unpriced dimensions remain unavailable rather than becoming zero. Effective rate is the interval cost converted to an hourly equivalent, including for storage.</span></div></div><div className="table-wrap"><table><thead><tr><th>Observed start (UTC)</th><th>Observed end (UTC)</th><th>Duration</th><th>Basis</th><th>Calculation reason</th><th>Effective rate</th><th>Cost</th></tr></thead><tbody>{history.intervals.map((row,index)=><tr key={`${row.usage_start}-${index}`}><td>{row.usage_start}</td><td>{row.usage_end}</td><td>{duration(row.duration_seconds)}</td><td>{row.basis}</td><td>{row.reason}</td><td>{row.effective_hourly_usd===null?"Unavailable":`${showMoney(row.effective_hourly_usd)}/hour equiv.`}</td><td>{showMoney(row.amount_usd)}</td></tr>)}</tbody></table></div>{history.intervals.length===0&&<p>No team-attributed observations exist for this resource in the selected range.</p>}</article>}
  </div>;
}
