"use client";

import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Plus,ShieldCheck,Tags,Trash2,Users} from "lucide-react";
import {request} from "./management";

type Rule={key:string;operator:"EQUALS"|"NOT_EQUALS"|"EXISTS"|"NOT_EXISTS";value:string};
type TagNode={kind:"tag";key:string;operator:Rule["operator"];value?:string};
type GroupNode={kind:"group";operator:"AND"|"OR";conditions:(TagNode|GroupNode)[]};
type FilterExpression=GroupNode;
type Team={id:string;name:string;amount_usd:string;filter_expression:FilterExpression;resource_count:number;resources_with_rates:number;intervals:number;priced_intervals:number;unresolved_intervals:number;observed_subtotal_usd:string|null;evaluation_status:string};
type Resource={id:string;name:string|null;provider_resource_id:string;provider_resource_type:string;region:string;availability_zone:string|null;state:string;last_seen:string;metadata:{tags?:Record<string,string>;pricing?:{status?:string}}};
type TeamList={period_start:string;period_end:string;teams:Team[];alerts_evaluated:false};
type Preview={matching_resources:number;sample:{id:string;name:string|null;provider_resource_id:string;provider_resource_type:string;region:string;state:string;pricing_status:string|null}[];sample_limit:number};
type TeamResources={team_id:string;team_name:string;filter_expression:FilterExpression;resources:Resource[]};

const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:6});
const blankRule=():Rule=>({key:"Team",operator:"EQUALS",value:""});
const showMoney=(value:string|null)=>value===null?"Unavailable":money.format(Number(value));
function expression(operator:"AND"|"OR",rules:Rule[]):FilterExpression{return {kind:"group",operator,conditions:rules.map(rule=>({kind:"tag",key:rule.key.trim(),operator:rule.operator,...(rule.operator==="EQUALS"||rule.operator==="NOT_EQUALS"?{value:rule.value.trim()}:{})}))};}
function describeNode(node:TagNode|GroupNode):string{if(node.kind==="group")return `(${node.conditions.map(describeNode).join(` ${node.operator} `)})`;return node.operator==="EXISTS"?`${node.key} exists`:node.operator==="NOT_EXISTS"?`${node.key} is absent`:`${node.key} ${node.operator==="EQUALS"?"=":"≠"} ${node.value}`;}
function describeFilter(filter:FilterExpression){const value=describeNode(filter);return value.slice(1,-1);}

export function LiveTeams({account,range,revision,onCreated}:{account:string;range:string;revision:number;onCreated?:()=>void}){
  const [data,setData]=useState<TeamList|null>(null);const [selected,setSelected]=useState("");const [resources,setResources]=useState<TeamResources|null>(null);
  const [name,setName]=useState("");const [amount,setAmount]=useState("");const [operator,setOperator]=useState<"AND"|"OR">("AND");const [rules,setRules]=useState<Rule[]>([blankRule()]);
  const [preview,setPreview]=useState<Preview|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [saved,setSaved]=useState(0);
  const filter=useMemo(()=>expression(operator,rules),[operator,rules]);
  const valid=rules.length>0&&rules.every(rule=>rule.key.trim()&&((rule.operator==="EXISTS"||rule.operator==="NOT_EXISTS")||rule.value.trim()));
  useEffect(()=>{if(!account||!range)return;let active=true;const [start,end]=range.split("/");request<TeamList>(`/api/v1/accounts/${account}/teams?start_date=${start}&end_date=${end}`).then(result=>{if(active){setData(result);setError("");}}).catch(reason=>{if(active)setError(reason.message);});return()=>{active=false;};},[account,range,revision,saved]);
  async function previewMatches(){if(!valid)return;setBusy("preview");setError("");try{setPreview(await request<Preview>(`/api/v1/accounts/${account}/teams/preview`,{method:"POST",body:JSON.stringify({filter_expression:filter})}));}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  async function saveTeam(event:React.FormEvent){event.preventDefault();if(!valid)return;setBusy("save");setError("");try{await request(`/api/v1/accounts/${account}/teams`,{method:"POST",body:JSON.stringify({name,amount_usd:amount,filter_expression:filter})});setName("");setAmount("");setRules([blankRule()]);setOperator("AND");setPreview(null);setSaved(value=>value+1);onCreated?.();}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  async function openTeam(team:Team){setSelected(team.id);setBusy(`team:${team.id}`);setError("");try{setResources(await request<TeamResources>(`/api/v1/accounts/${account}/teams/${team.id}/resources`));}catch(reason){setError((reason as Error).message);}finally{setBusy("");}}
  function changeRule(index:number,patch:Partial<Rule>){setRules(current=>current.map((rule,position)=>position===index?{...rule,...patch}:rule));setPreview(null);}
  if(!account)return <article className="panel management"><h2>Teams</h2><p>Select a connected AWS account first.</p></article>;
  return <div className="live-teams">
    <div className="guardrail amber"><ShieldCheck/><div><b>Team matching is live; alarm evaluation is withheld</b><span>Current resources use their latest tags. Observed cost intervals use the tags recorded at the time of each interval.</span></div><span>NO ALERTS</span></div>
    {error&&<div className="guardrail error" role="alert"><AlertTriangle/><div><b>Team operation failed</b><span>{error}</span></div></div>}
    <article className="panel team-builder"><div className="panel-head"><div><h2>Create team</h2><span>Local definition for this AWS account</span></div></div>
      <form onSubmit={saveTeam}><div className="team-basics"><label>Team name<input required maxLength={100} value={name} onChange={event=>setName(event.target.value)} placeholder="HPC Production"/></label><label>Monthly limit (USD)<input required type="number" min="0.01" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="5000.00"/></label></div>
        <div className="rule-heading"><div><b>Resource tag conditions</b><span>Every rule is evaluated exactly and case-sensitively against AWS tag keys and values.</span></div><label>Match<select value={operator} onChange={event=>{setOperator(event.target.value as "AND"|"OR");setPreview(null);}}><option value="AND">ALL conditions (AND)</option><option value="OR">ANY condition (OR)</option></select></label></div>
        <div className="rule-list">{rules.map((rule,index)=><div className="rule-row" key={index}><span>{index===0?"WHERE":operator}</span><input aria-label={`Tag key ${index+1}`} required value={rule.key} onChange={event=>changeRule(index,{key:event.target.value})} placeholder="Tag key"/><select aria-label={`Comparison ${index+1}`} value={rule.operator} onChange={event=>changeRule(index,{operator:event.target.value as Rule["operator"]})}><option value="EQUALS">equals</option><option value="NOT_EQUALS">does not equal</option><option value="EXISTS">exists</option><option value="NOT_EXISTS">does not exist</option></select>{(rule.operator==="EQUALS"||rule.operator==="NOT_EQUALS")&&<input aria-label={`Tag value ${index+1}`} required value={rule.value} onChange={event=>changeRule(index,{value:event.target.value})} placeholder="Tag value"/>}<button type="button" className="icon-action" disabled={rules.length===1} onClick={()=>{setRules(current=>current.filter((_,position)=>position!==index));setPreview(null);}} aria-label={`Remove condition ${index+1}`}><Trash2/></button></div>)}</div>
        <div className="builder-actions"><button type="button" onClick={()=>setRules(current=>[...current,blankRule()])} disabled={rules.length>=20}><Plus/>Add condition</button><button type="button" disabled={!valid||Boolean(busy)} onClick={previewMatches}>{busy==="preview"?"Checking…":"Preview matched resources"}</button><button type="submit" disabled={!valid||!name.trim()||!amount||Boolean(busy)}>{busy==="save"?"Creating…":"Create team and limit"}</button></div>
      </form>
      {preview&&<div className="match-preview"><b>{preview.matching_resources} current resources match</b><span>{describeFilter(filter)}</span>{preview.matching_resources===0&&<em>No team will be created until you explicitly submit; check exact tag casing and values.</em>}<div className="preview-chips">{preview.sample.map(row=><span key={row.id}>{row.provider_resource_type.toUpperCase()} · {row.name||row.provider_resource_id}</span>)}</div>{preview.matching_resources>preview.sample_limit&&<small>Showing the first {preview.sample_limit} resources.</small>}</div>}
    </article>
    <div className="team-grid live-team-grid">{data?.teams.map(team=>{const coverage=team.intervals?team.priced_intervals/team.intervals*100:0;return <button className={`panel team-card team-select ${selected===team.id?"selected":""}`} key={team.id} onClick={()=>void openTeam(team)}><div className="team-head"><span><Users/></span><div><h2>{team.name}</h2><p>{describeFilter(team.filter_expression)}</p></div><span className="pill warning">WITHHELD</span></div><strong>{showMoney(team.observed_subtotal_usd)} <small>/ {showMoney(team.amount_usd)}</small></strong><div className="team-facts"><span><b>{team.resource_count}</b> current resources</span><span><b>{coverage.toFixed(1)}%</b> priced intervals</span><span><b>{team.unresolved_intervals}</b> unresolved intervals</span></div><small>{busy===`team:${team.id}`?"Loading resources…":"Open matched resources"}</small></button>;})}</div>
    {data&&data.teams.length===0&&<article className="panel empty-team"><Tags/><h2>No teams configured</h2><p>Create a team above, preview the exact tag match, then save its monthly limit.</p></article>}
    {resources&&<article className="panel table-panel team-resources"><div className="panel-head"><div><h2>{resources.team_name} resources</h2><span>{resources.resources.length} current exact matches · {describeFilter(resources.filter_expression)}</span></div></div><div className="table-wrap"><table><thead><tr><th>Resource</th><th>Service</th><th>Region / AZ</th><th>State</th><th>Rate status</th><th>Last observed</th></tr></thead><tbody>{resources.resources.map(row=><tr key={row.id}><td><b>{row.name||row.provider_resource_id}</b><br/><small>{row.provider_resource_id}</small></td><td>{row.provider_resource_type.toUpperCase()}</td><td>{row.region}{row.availability_zone?` / ${row.availability_zone}`:""}</td><td>{row.state}</td><td>{row.metadata.pricing?.status??"UNRESOLVED"}</td><td>{row.last_seen}</td></tr>)}</tbody></table></div>{resources.resources.length===0&&<p>No current resources match this team definition.</p>}</article>}
  </div>;
}
