"use client";
import { useState } from "react";
import { buildAwsOnboardingTemplate, validateAwsOnboarding } from "./aws-onboarding";
export function Accounts() {
  const [accountName,setAccountName]=useState(""); const [accountId,setAccountId]=useState(""); const [region,setRegion]=useState("us-east-1");
  const [cn,setCn]=useState("cloudscope-test-collector"); const [certificate,setCertificate]=useState(""); const [message,setMessage]=useState("");
  const generate=()=>{const input={accountName,accountId,region,certificateCommonName:cn,caCertificatePem:certificate};const error=validateAwsOnboarding(input);if(error){setMessage(error);return;}const blob=new Blob([buildAwsOnboardingTemplate(input)],{type:"application/x-yaml"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`cloudscope-${accountName.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-")}-onboarding.yaml`;link.click();URL.revokeObjectURL(url);setMessage("Template generated. Deploy it only in the account and region entered above.");};
  return <article className="panel management"><h2>Add AWS account</h2><p>Generate the AWS-side CloudFormation stack for a test account. The public CA certificate is embedded in the template; private keys stay on this VM.</p><div className="onboarding-grid"><label>Account name<input value={accountName} onChange={e=>setAccountName(e.target.value)} placeholder="Engineering Sandbox"/></label><label>AWS account ID<input value={accountId} onChange={e=>setAccountId(e.target.value.replace(/\D/g,"").slice(0,12))} inputMode="numeric" placeholder="123456789012"/></label><label>AWS region<input value={region} onChange={e=>setRegion(e.target.value)} placeholder="us-east-1"/></label><label>Collector certificate CN<input value={cn} onChange={e=>setCn(e.target.value)}/></label><label className="full">Public CA certificate (PEM)<textarea value={certificate} onChange={e=>setCertificate(e.target.value)} rows={8} placeholder={'-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----'}/><small>Use test-ca-fixed.crt. Never paste collector.key, test-ca.key, access keys, or secrets.</small></label></div><button type="button" onClick={generate}>Download CloudFormation template</button><p role="status">{message}</p><h3>Template resources</h3><p>Restricted collector role, IAM Roles Anywhere trust anchor and profile, and a dedicated SNS topic. After deployment, retain the stack outputs for the collector connection step.</p></article>;
}
export function AlertHistory() {
  return <article className="panel management"><h2>Alert history</h2><p>No real alerts have been sent. Live SNS delivery is disabled.</p><p>The warning cards in the demo are illustrative scenarios, not delivery receipts. There are no SNS message IDs or Lambda invocation results to show.</p></article>;
}
export function Settings() {
  const [density,setDensity]=useState("comfortable");
  const [message,setMessage]=useState("");
  return <article className="panel management"><h2>Display settings</h2><p>Device-local preferences only. This does not configure collectors, team limits, or alarm delivery.</p><form onSubmit={e=>{e.preventDefault();try {localStorage.setItem("cloudscope-density",density);document.documentElement.dataset.density=density;setMessage("Display preference saved on this device.");}catch{setMessage("Your browser blocked saving this preference.");}}}><label>Table spacing<select value={density} onChange={e=>setDensity(e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><button type="submit">Save display preference</button><button type="button" onClick={()=>{try{const value=localStorage.getItem("cloudscope-density")==="compact"?"compact":"comfortable";setDensity(value);document.documentElement.dataset.density=value;setMessage("Saved preference loaded and applied.");}catch{setMessage("Saved preferences unavailable.");}}}>Load saved preference</button><p role="status">{message}</p></form><h3>Production configuration</h3><p>Collection scheduling, RBAC, pricing refresh, and SNS configuration remain unavailable in this demo.</p></article>;
}
